select *
from PUBLIC.SUMMARY_ANALYTICS SA
inner join PUBLIC.DWR_DATE DD on
SA.DAY_KEY = DD.CALENDAR_DATE ;

SELECT MO_KEY, ACCOUNT_TYPE , SUM(TOTAL_SPENT) , SUM(TOTAL_TRANSACTIONS)
FROM PUBLIC.SUMMARY_ANALYTICS SA
INNER JOIN PUBLIC.DWR_DATE DD ON
SA.DAY_KEY = DD.CALENDAR_DATE
GROUP BY MO_KEY, ACCOUNT_TYPE
ORDER BY MO_KEY ASC , ACCOUNT_TYPE ASC;

SELECT MO_KEY, SERVICE_NAME , SUM(TOTAL_SPENT) , SUM(TOTAL_TRANSACTIONS)
FROM PUBLIC.SUMMARY_ANALYTICS SA
INNER JOIN PUBLIC.DWR_DATE DD ON
SA.DAY_KEY = DD.CALENDAR_DATE
GROUP BY MO_KEY, SERVICE_NAME
ORDER BY MO_KEY ASC , SERVICE_NAME ASC;

SELECT MO_KEY , CALENDAR_DATE , C.CITY_NAME , SERVICE_NAME , SUM(TOTAL_SPENT) , SUM(TOTAL_TRANSACTIONS)
FROM PUBLIC.SUMMARY_ANALYTICS SA
INNER JOIN PUBLIC.DWR_DATE DD ON
SA.DAY_KEY = DD.CALENDAR_DATE
INNER JOIN PUBLIC.CITIES C ON
C.CODE = SA.CITY_CODE
GROUP BY MO_KEY , CALENDAR_DATE , C.CITY_NAME, SERVICE_NAME
ORDER BY MO_KEY , CALENDAR_DATE , C.CITY_NAME, SERVICE_NAME;